### ISSUE TITLE
RuntimeException: “Stub!” without any other information

### ISSUE THREAD

**Issue by SerwusX** [NewtronLabs/EasyBluetooth#3]
I put details on [stackoverflow](https://stackoverflow.com/questions/51023865/runtimeexception-stub-without-any-other-information).

**Comment by SerwusX** [comment]
Here I put additional logcat output.

`    Process: XXX, PID: 28033
    java.lang.RuntimeException: Unable to start activity ComponentInfo{XXX/XXX.Activities.MasterActivity}: java.lang.RuntimeException: Stub!
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6342)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
     Caused by: java.lang.RuntimeException: Stub!
        at com.newtronlabs.easybluetooth.BluetoothServer$Builder.<init>(Unknown Source)
        at XXX.Activities.MasterActivity.createBluetoothServer(MasterActivity.java:36)
        at XXX.Activities.MasterActivity.onCreate(MasterActivity.java:28)
        at android.app.Activity.performCreate(Activity.java:6847)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2785) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.app.ActivityThread.main(ActivityThread.java:6342) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770) `

Maybe you will be able to help me, because library looks really good and I look forward to use it. :)

**Comment by NewtronLabs** [comment]
Hi @SerwusX,

We left a comment on the StackOverflow page that you mentioned. Please post your gradle file on the StackOverflow since you started the question there others might also find it helpful. We will promptly help you solve the issue. We already have some ideas as to what is going on :).

Thank you for contacting us, we are here to help.

Thanks,
Newtron Labs

**Comment by SerwusX** [comment]
Thank You for fast reply! I've edited my answer on stackoverflow.

**Comment by SerwusX** [comment]
Answer on stackoverflow is correct! Thank You. Issue can be closed I think.

**Comment by NewtronLabs** [comment]
Hi @SerwusX!
 
Happy to hear and glad to help!
 
Let us know if you have any more questions,

Newtron Labs
Easy Bluetooth Team
Solving problems so you don't have to.
