### ISSUE TITLE
java.lang.OutOfMemoryError: Failed to allocate a 1207959568 byte

### ISSUE THREAD

**Issue by paloky** [NewtronLabs/EasyBluetooth#5]
Hi.
I receive the same bug as    GrishinSergey commented on 24 Sep 2018.
I only send 1 byte to App. !!!

Any solution?
Thanks a lot.

java.lang.OutOfMemoryError: Failed to allocate a 1207959568 byte allocation with 12582912 free bytes and 190MB until OOM, max allowed footprint 14280832, growth limit 201326592
        at com.newtronlabs.easybluetooth.d.c.run(Unknown Source:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by NewtronLabs** [comment]
Hi @paloky,

Could you share with us the code that you are using to send and receive data? Also what are the specs of the two devices you are using? 

Thank you,
Newtron Labs
